com:
    resource: "@ComBundle/Resources/config/routing.yml"
    prefix:   /com/

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

app:
    resource: @AppBundle/Controller/
    type:     annotation
    
_homepage:
    pattern: /
    defaults: { _controller: AppBundle:Default:index }

