com_homepage:
    path:     /main/
    defaults: { _controller: ComBundle:Default:index }
    
com_ips_square_suggest:
    path:     /ips-square-suggest/
    defaults: { _controller: ComBundle:IpsSquareSuggest:render }

com_ips_square_search:
    pattern:  /ips-square-search/{items}/{page}
    defaults: { _controller: ComBundle:IpsSquareSearch:renderResult, items: 100, page : 1}

square_suggest:
    path: /ips-square-suggest/suggestion
    defaults: { _controller: ComBundle:IpsSquareSuggest:suggest }
    requirements:
        _method: POST
    
com_ips_file_post:
    path:     /ips-file-post/
    defaults: { _controller: ComBundle:IpsFilePost:render }
    
comFilePost:
    path: /ips-file-post/post
    defaults: { _controller: ComBundle:IpsFilePost:post }
    requirements:
        _method: POST

com_ips_untrusted_fuzzy_search:
    path:     /ips-untrusted-fuzzy-search/
    defaults: { _controller: ComBundle:IpsUntrustedFuzzySearch:render }

comUntrustedFuzzySearch:
    path: /ips-untrusted-fuzzy-search/search
    defaults: { _controller: ComBundle:IpsUntrustedFuzzySearch:search, refresh: YES , items: 100, page : 1}
    requirements:
        _method: POST